modLoader = "javafml"
loaderVersion = "*"
license = "${license}"
issueTrackerURL = "https://github.com/${github}/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = "${description}"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "${id}-common.mixins.json"